[project]
name = "mid-level-python"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.14",
  "pydantic==2.11.7",
  "sqlalchemy==2.0.41",
  "uvicorn[standard]==0.34.3",
]

[project.optional-dependencies]
dev = [
  "httpx==0.28.1",
  "pytest==8.4.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
