// // Mock data for employees, categories, and expenses
// export const mockEmployees = [
//   {
//     name: 'John Smith',
//     email: 'john.smith@company.co.uk',
//     role: 'Manager',
//   },
//   {
//     name: 'Sarah Johnson',
//     email: 'sarah.johnson@company.co.uk',
//     role: 'Developer',
//   },
//   {
//     name: 'Mike Brown',
//     email: 'mike.brown@company.co.uk',
//     role: 'Designer',
//   },
//   {
//     name: 'Emma Wilson',
//     email: 'emma.wilson@company.co.uk',
//     role: 'Admin',
//   },
// ]

// export const mockCategories = [
//   { name: 'Travel', active: true },
//   { name: 'Meals', active: true },
//   { name: 'Office Supplies', active: true },
//   { name: 'Software', active: true },
//   { name: 'Training', active: true },
//   { name: 'Equipment', active: false },
//   { name: 'Marketing', active: true },
// ]

// export const mockExpenses = [
//   {
//     employeeId: 1,
//     amount: '125.50',
//     category: 'Travel',
//     description: 'Train tickets to London',
//     date: '2025-06-10',
//     status: 'Pending',
//     receipt: 'receipt1.pdf',
//   },
//   {
//     employeeId: 2,
//     amount: '45.00',
//     category: 'Meals',
//     description: 'Client lunch',
//     date: '2025-06-08',
//     status: 'Approved',
//     receipt: null,
//   },
//   {
//     employeeId: 1,
//     amount: '89.99',
//     category: 'Software',
//     description: 'Design tool subscription',
//     date: '2025-06-05',
//     status: 'Approved',
//     receipt: 'receipt2.pdf',
//   },
//   {
//     employeeId: 3,
//     amount: '15.75',
//     category: 'Office Supplies',
//     description: 'Notebooks and pens',
//     date: '2025-05-28',
//     status: 'Rejected',
//     receipt: null,
//   },
//   {
//     employeeId: 2,
//     amount: '200.00',
//     category: 'Training',
//     description: 'React conference ticket',
//     date: '2025-05-25',
//     status: 'Approved',
//     receipt: 'receipt3.pdf',
//   },
//   {
//     employeeId: 4,
//     amount: '67.30',
//     category: 'Travel',
//     description: 'Taxi to airport',
//     date: '2025-06-12',
//     status: 'Pending',
//     receipt: null,
//   },
//   {
//     employeeId: 3,
//     amount: '12.50',
//     category: 'Meals',
//     description: 'Coffee with client',
//     date: '2025-06-14',
//     status: 'Pending',
//     receipt: null,
//   },
//   {
//     employeeId: 1,
//     amount: '450.00',
//     category: 'Equipment',
//     description: 'Wireless headphones',
//     date: '2025-06-01',
//     status: 'Approved',
//     receipt: 'receipt4.pdf',
//   },
//   {
//     employeeId: 2,
//     amount: '25.00',
//     category: 'Office Supplies',
//     description: 'USB cables',
//     date: '2025-05-20',
//     status: 'Approved',
//     receipt: null,
//   },
//   {
//     employeeId: 4,
//     amount: '180.75',
//     category: 'Travel',
//     description: 'Hotel booking',
//     date: '2025-05-15',
//     status: 'Approved',
//     receipt: 'receipt5.pdf',
//   },
// ]
